### PR TITLE
contrib-dom0: ensure to import key after install

### PR DESCRIPTION
**Pull request by fepitre**
Attempt to solve https://forum.qubes-os.org/t/qubes-repo-contrib-question/1233/4

### CODE REVIEW

**Comment by marmarek** [comment]
I'm afraid it won't work, the rpmdb is locked when package is installed. We try to work around it in `qubes-release` package by calling `systemd-run --on-active=5min rpm --import ...`, although that will work with a delay.

**Comment by fepitre** [comment]
Oh no...

**Review by marmarek — APPROVED** [review]

**Comment by tlaurion** [comment]
@fepitre @marmarek : is this supposed to result in an updated qubes-repo-contrib package?

**Comment by tlaurion** [comment]
Maybe reopen https://github.com/QubesOS/qubes-issues/issues/6124 until this is fixed? Cross-linking.

**Pull request merged**
